apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-triggertemplate-qa
  namespace: uxie-cicd
spec:
  params:
    - name: git-url
      description: Git repository URL (SSH)
    - name: git-revision
      description: Git revision (refs/heads/main)
    - name: git-repo-name
      description: Repository name
    - name: git-commit-sha
      description: Commit SHA
    - name: git-commit-author
      description: Commit author
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.git-repo-name)-qa-
        namespace: uxie-cicd
        labels:
          tekton.dev/pipeline: main-pipeline
          app.kubernetes.io/name: $(tt.params.git-repo-name)
          app.kubernetes.io/environment: qa
      spec:
        pipelineRef:
          name: main-pipeline
        params:
          - name: applicationName
            value: $(tt.params.git-repo-name)
          - name: gitRepoUrl
            value: $(tt.params.git-url)
          - name: gitRevision
            value: $(tt.params.git-revision)
          - name: environment
            value: qa
          - name: enabledLintSonar
            value: "true"
          - name: ignoreLinterFailures
            value: "false"
          - name: ignoreTestFailures
            value: "false"
          - name: ignoreScanFailures
            value: "false"
          - name: ignoreQualityGate
            value: "false"
        workspaces:
          - name: data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 2Gi
          - name: ssh-creds
            secret:
              secretName: git-ssh-credentials
