apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-trigger-dev-react
  namespace: uxie-cicd
spec:
  interceptors:
    - ref:
        name: github
        kind: ClusterInterceptor
      params:
        - name: secretRef
          value:
            secretName: github-webhook-secret
            secretKey: secret
        - name: eventTypes
          value: ["push"]
    - ref:
        name: cel
        kind: ClusterInterceptor
      params:
        - name: filter
          # Filter for develop branch AND React repos (chat-web, documents-web)
          value: >-
            body.ref == "refs/heads/develop" &&
            (body.repository.name == "uxie-chat-web" ||
             body.repository.name == "uxie-documents-web")
        - name: overlays
          value:
            - key: git-url
              expression: "body.repository.ssh_url"
            - key: git-revision
              expression: "body.ref"
            - key: git-repo-name
              expression: "body.repository.name"
            - key: git-commit-sha
              expression: "body.after"
            - key: git-commit-author
              expression: "body.pusher.name"
  bindings:
    - ref: github-push-binding
  template:
    ref: github-triggertemplate-dev-react
