apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: main-pipeline
  namespace: uxie-cicd
spec:
  description: |
    Orchestrator pipeline that reads ocp-config.yaml from source repo
    and routes to the appropriate tech-specific pipeline (java/python/react).
  params:
    - name: applicationName
      description: Application name
      type: string
    - name: gitRepoUrl
      description: Git repository URL (SSH)
      type: string
    - name: gitRevision
      description: Git revision (refs/heads/develop or refs/heads/main)
      type: string
    - name: environment
      description: Target environment (dev/qa)
      type: string
    - name: enabledLintSonar
      description: Enable linting and SonarQube scan
      type: string
      default: "true"
    - name: ignoreLinterFailures
      description: Ignore linter failures
      type: string
      default: "true"
    - name: ignoreTestFailures
      description: Ignore test failures
      type: string
      default: "true"
    - name: ignoreScanFailures
      description: Ignore SonarQube scan failures
      type: string
      default: "true"
    - name: ignoreQualityGate
      description: Ignore quality gate failures
      type: string
      default: "true"
    - name: sourceContextDir
      description: Source code context directory
      type: string
      default: source
    - name: nexusURL
      description: Nexus mirror URL
      type: string
      default: http://nxrm-ha-nexus-repo-service.nexus.svc.cluster.local:80/repository/maven-public/
    - name: sonarUrl
      description: SonarQube URL
      type: string
      default: http://sonarqube-sonarqube.sonarqube.svc.cluster.local:9000
  workspaces:
    - name: data
    - name: ssh-creds
      optional: true
  tasks:
    # Step 1: Clone source repository
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.gitRepoUrl)
        - name: revision
          value: $(params.gitRevision)
        - name: subdirectory
          value: $(params.sourceContextDir)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: data
        - name: ssh-directory
          workspace: ssh-creds

    # Step 2: Read ocp-config.yaml and determine pipeline
    - name: get-pipeline-ref
      runAfter:
        - git-clone
      taskSpec:
        params:
          - name: appConfigPath
            type: string
          - name: gitRevision
            type: string
        results:
          - name: pipelineRef
            description: Pipeline to execute
          - name: projectName
            description: Project name from config
          - name: manifestGitUrl
            description: Manifest repository URL
          - name: imageName
            description: Image name
        workspaces:
          - name: data
        steps:
          - name: parse-config
            image: registry.access.redhat.com/ubi8/ubi-minimal:latest
            workingDir: $(workspaces.data.path)
            script: |
              #!/bin/bash
              set -e

              CONFIG_PATH="$(params.appConfigPath)"

              # Function to extract value from simple YAML
              get_yaml_value() {
                grep "^$1:" "$CONFIG_PATH" 2>/dev/null | cut -d':' -f2- | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//' | tr -d '"' || echo ""
              }

              if [ ! -f "$CONFIG_PATH" ]; then
                echo "WARNING: $CONFIG_PATH not found, using defaults"
                PIPELINE_REF="java-pipeline"
                PROJECT_NAME="uxie"
                MANIFEST_GIT_URL=""
                IMAGE_NAME="unknown"
              else
                PIPELINE_REF=$(get_yaml_value "pipelineRef")
                PROJECT_NAME=$(get_yaml_value "projectName")
                MANIFEST_GIT_URL=$(get_yaml_value "manifestGitUrl")
                IMAGE_NAME=$(get_yaml_value "imageName")

                # Set defaults if empty
                [ -z "$PIPELINE_REF" ] && PIPELINE_REF="java-pipeline"
                [ -z "$PROJECT_NAME" ] && PROJECT_NAME="uxie"
                [ -z "$IMAGE_NAME" ] && IMAGE_NAME="unknown"
              fi

              # Write results
              echo -n "$PIPELINE_REF" > $(results.pipelineRef.path)
              echo -n "$PROJECT_NAME" > $(results.projectName.path)
              echo -n "$MANIFEST_GIT_URL" > $(results.manifestGitUrl.path)
              echo -n "$IMAGE_NAME" > $(results.imageName.path)

              echo "Pipeline: $PIPELINE_REF"
              echo "Project: $PROJECT_NAME"
              echo "Manifest: $MANIFEST_GIT_URL"
              echo "Image: $IMAGE_NAME"
      params:
        - name: appConfigPath
          value: $(params.sourceContextDir)/ocp-config.yaml
        - name: gitRevision
          value: $(params.gitRevision)
      workspaces:
        - name: data
          workspace: data

    # Step 3: Start tech-specific pipeline using oc create
    - name: start-pipeline
      runAfter:
        - get-pipeline-ref
      taskSpec:
        params:
          - name: applicationName
            type: string
          - name: pipelineRef
            type: string
          - name: gitRepoUrl
            type: string
          - name: gitRevision
            type: string
          - name: environment
            type: string
          - name: manifestGitUrl
            type: string
          - name: imageName
            type: string
          - name: projectName
            type: string
          - name: enabledLintSonar
            type: string
          - name: ignoreLinterFailures
            type: string
          - name: ignoreTestFailures
            type: string
          - name: ignoreScanFailures
            type: string
          - name: ignoreQualityGate
            type: string
          - name: nexusURL
            type: string
          - name: sonarUrl
            type: string
        steps:
          - name: start
            image: registry.redhat.io/openshift4/ose-cli:latest
            script: |
              #!/bin/sh
              set -e

              PIPELINE_REF="$(params.pipelineRef)"
              APP_NAME="$(params.applicationName)"
              ENV="$(params.environment)"
              TIMESTAMP=$(date +%s | cut -c6-10)

              echo "=== Main Pipeline Orchestrator ==="
              echo "Pipeline: $PIPELINE_REF"
              echo "Application: $APP_NAME"
              echo "Environment: $ENV"
              echo "Manifest URL: $(params.manifestGitUrl)"
              echo "Image Name: $(params.imageName)"
              echo ""

              # Generate PipelineRun YAML
              cat << EOF | oc create -f -
              apiVersion: tekton.dev/v1
              kind: PipelineRun
              metadata:
                generateName: ${APP_NAME}-${ENV}-child-
                namespace: uxie-cicd
                labels:
                  tekton.dev/pipeline: ${PIPELINE_REF}
                  app.kubernetes.io/name: ${APP_NAME}
                  app.kubernetes.io/environment: ${ENV}
                  spawned-by: main-pipeline
              spec:
                pipelineRef:
                  name: ${PIPELINE_REF}
                params:
                  - name: applicationName
                    value: "${APP_NAME}"
                  - name: gitRepoUrl
                    value: "$(params.gitRepoUrl)"
                  - name: gitRevision
                    value: "$(params.gitRevision)"
                  - name: environment
                    value: "${ENV}"
                  - name: manifestGitUrl
                    value: "$(params.manifestGitUrl)"
                  - name: imageName
                    value: "$(params.imageName)"
                  - name: projectName
                    value: "$(params.projectName)"
                  - name: enabledLintSonar
                    value: "$(params.enabledLintSonar)"
                  - name: ignoreLinterFailures
                    value: "$(params.ignoreLinterFailures)"
                  - name: ignoreTestFailures
                    value: "$(params.ignoreTestFailures)"
                  - name: ignoreScanFailures
                    value: "$(params.ignoreScanFailures)"
                  - name: ignoreQualityGate
                    value: "$(params.ignoreQualityGate)"
                workspaces:
                  - name: data
                    volumeClaimTemplate:
                      spec:
                        accessModes:
                          - ReadWriteOnce
                        resources:
                          requests:
                            storage: 2Gi
                  - name: ssh-creds
                    secret:
                      secretName: git-ssh-credentials
                  - name: maven-settings
                    emptyDir: {}
              EOF

              echo ""
              echo "Child pipeline $PIPELINE_REF started successfully"
              echo "Check status: oc get pipelinerun -l spawned-by=main-pipeline -n uxie-cicd"
      params:
        - name: applicationName
          value: $(params.applicationName)
        - name: pipelineRef
          value: $(tasks.get-pipeline-ref.results.pipelineRef)
        - name: gitRepoUrl
          value: $(params.gitRepoUrl)
        - name: gitRevision
          value: $(params.gitRevision)
        - name: environment
          value: $(params.environment)
        - name: manifestGitUrl
          value: $(tasks.get-pipeline-ref.results.manifestGitUrl)
        - name: imageName
          value: $(tasks.get-pipeline-ref.results.imageName)
        - name: projectName
          value: $(tasks.get-pipeline-ref.results.projectName)
        - name: enabledLintSonar
          value: $(params.enabledLintSonar)
        - name: ignoreLinterFailures
          value: $(params.ignoreLinterFailures)
        - name: ignoreTestFailures
          value: $(params.ignoreTestFailures)
        - name: ignoreScanFailures
          value: $(params.ignoreScanFailures)
        - name: ignoreQualityGate
          value: $(params.ignoreQualityGate)
        - name: nexusURL
          value: $(params.nexusURL)
        - name: sonarUrl
          value: $(params.sonarUrl)
